name: 'Deploy Scheduler'

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
   
      - name: Check turbo-ignore for changes
        id: turbo_ignore
        continue-on-error: true
        run: |
          npx turbo-ignore scheduler 2> turbo_ignore_error.log
  
      - name: Upload turbo-ignore error log
        if: steps.turbo_ignore.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: turbo-ignore-error-log
          path: turbo_ignore_error.log

      - name: Railway Deploy
        if: steps.turbo_ignore.outcome == 'failure'
        uses: bervProject/railway-deploy@0.1.2-beta
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "scheduler"

